{% set name = "py4vasp" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py4vasp-{{ version }}.tar.gz
  sha256: 85305d4f47393530544e4365c77c6faa31eca5bd322baa7b110b439913f07b52

build:
  entry_points:
    - error-analysis = py4vasp.scripts.error_analysis:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.23
    - h5py >=3.7.0
    - pandas >=1.4.3
    - nglview >=3.0.5
    - ase >=3.22.1
    - plotly >=5.9.0
    - python-kaleido !=0.2.1.post1,>=0.2.1
    - ipython >=8.12
    - notebook

test:
  imports:
    - py4vasp
  commands:
    - pip check
    - error-analysis --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://vasp.at/py4vasp/latest
  summary: Tool for assisting with the analysis and setup of VASP calculations.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martin-schlipf
    - jan-janssen
