{% set name = "py4vasp" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py4vasp-{{ version }}.tar.gz
  sha256: 11c1f40bc9f11bc5e4d736745922c0b99f4bb668ee7eb21146a161381cb9dd5e

build:
  entry_points:
    - error-analysis = py4vasp.scripts.error_analysis:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<3.12
    - numpy >=1.23.0
    - h5py >=3.7.0
    - pandas >=1.4.3
    - nglview >=3.0.5
    - ase >=3.22.1
    - plotly >=5.9.0
    - python-kaleido !=0.2.1.post1,>=0.2.1
    - ipython >=8.12

test:
  imports:
    - py4vasp
  commands:
    - pip check
    - error-analysis --help
  requires:
    - pip

about:
  home: https://vasp.at/py4vasp/latest
  summary: Tool for assisting with the analysis and setup of VASP calculations.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martin-schlipf
    - jan-janssen
